### ISSUE TITLE
tilt and yaw speed

### ISSUE THREAD

**Issue by brandonforster** [ahoran3/CAP4720-Project2#5]
Tilt and yaw are really slow on the big models like Parliament and too fast on the cube. Figure out a way to scale the change with the size of the object.

**Comment by jonnycools** [comment]
I'm current working on this, I think i found a way to make this work. I'm building it into the camera. If you have it working commit and i'll work it into my code

**Comment by brandonforster** [comment]
I've got a tilt and yaw working, but it needs to move with a variable
speed. I haven't got anything for that, if you do go for it.

On Wed, Oct 16, 2013 at 8:16 PM, jonnycools notifications@github.comwrote:

> I'm current working on this, I think i found a way to make this work. I'm
> building it into the camera. If you have it working commit and i'll work it
> into my code
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ahoran3/CAP4720-Project2/issues/5#issuecomment-26470396
> .

## 

Brandon Forster

**Comment by jonnycools** [comment]
I'm on it.

**Comment by jonnycools** [comment]
One question when i move left or right should i translate the model or rotate it in the direction?
I'm leaning towards rotating

**Comment by brandonforster** [comment]
What's "moving"? We have several different types of movement that are all very different. Please be more specific.

If you're talking about yaw, what we see with the code in master is exactly how it should look.

http://3.bp.blogspot.com/_HWNuU41CrJE/S9dTGUNszBI/AAAAAAAAAC8/vmFMOYrWfpA/s1600/Roll_Pitch_Yaw.jpg

**Comment by brandonforster** [comment]
(also what they're calling "pitch" we're calling "tilt")

**Comment by ahoran3** [comment]
All we need to do in order to have the camera's movement seem relatively the same on all objects is to multiply each movement by some factor of the entire objects size. For example, last night I made the zoom effect proportional to the object by adding/subtracting a value called "zoomDelta" (which is the same fraction of size of the object's diameter in each model) to the current Field of View.

I understand the camera movements more than the lighting, so I'll focus on a  few of the other camera functions we still have to do. I'll start with Trucked and Dollied (W,A,S,D keys)

From: Brandon Forster
Sent: ?Wednesday?, ?October? ?16?, ?2013 ?8?:?57? ?PM
To: ahoran3/CAP4720-Project2

(also what they're calling "pitch" we're calling "tilt")

##

**Comment by jonnycools** [comment]
give me a couple of minutes here, i think i have the solution

**Comment by mhansendev** [comment]
I just finished the pedestal functions.  Truck and dolly are almost 
identical... working on pushing now

**Comment by mhansendev** [comment]
Sorry about the delay... it should be up now

**Comment by jonnycools** [comment]
I just did zoom and rotations

**Comment by ahoran3** [comment]
Zoom, Pitch, and Yaw we're the only ones already done...

From: jonnycools
Sent: ?Wednesday?, ?October? ?16?, ?2013 ?9?:?23? ?PM
To: ahoran3/CAP4720-Project2
Cc: ahoran3

I just did zoom and rotations

##

**Comment by jonnycools** [comment]
I'm pretty sure someone just deleted my branch

**Comment by brandonforster** [comment]
Looks like you're right. Just make a new one, you didn't have any commits on it right?

**Comment by jonnycools** [comment]
yes it did, its all gone!

**Comment by brandonforster** [comment]
I don't know what to tell you dude. I didn't do anything that would touch your branch. You still have the code locally, right?

**Comment by jonnycools** [comment]
i'm over it, I'm redoing it

**Comment by brandonforster** [comment]
Okay. Make sure to make really small commits and sync them with the GitHub server often. Outside of that, I don't know what to tell you.

**Comment by ahoran3** [comment]
I'm having an issue with git right now, so I'm attaching this here. This is the updated Camera file for consistent movement & angle speeds.

From: Jonathan Cools-Lartigue
Sent: ?Wednesday?, ?October? ?16?, ?2013 ?11?:?33? ?PM
To: Matthew Hansen
Cc: Brandon Forster, Alex Horan

I've taken to the book on lighting. I moved the calculations to the fragment shader.

Sent from my iPhone

On Oct 16, 2013, at 11:05 PM, Matthew Hansen <m.hansen@knights.ucf.edu<mailto:m.hansen@knights.ucf.edu>> wrote:

Actually, the omni light was PA5 and we need to implement a spotlight if I'm not mistaken.

On 10/16/2013 11:01 PM, Brandon Forster wrote:
Absolutely brilliant work on that camera. We should really do something about the speed, but it technically works so let's put that off for now.

Looking over the light code that we have so far, this is based on your PA5 with a spotlight, correct Matt? We just need to implement an omni light and switch between them. The project description says nothing about moving the light, so I think we can pass on that.

On Wed, Oct 16, 2013 at 10:49 PM, Matthew Hansen <mhansen@cfl.rr.com<mailto:mhansen@cfl.rr.com>> wrote:
I just got all of the camera functions working (however the speed still isn't based on the scale of the object).  I'll push within 5 minutes.

On 10/16/2013 10:40 PM, Brandon Forster wrote:
Okay, so I've been reading tutorials and that issue thread and I'm a bit lost. Who is working on what, and what should I be doing so I'm not duplicating work?

## 

Brandon Forster

## 

Brandon Forster
